# Generated by Django 5.1.3 on 2024-11-23 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_id', models.IntegerField(default=0)),
                ('customer_code', models.CharField(default='', max_length=25)),
                ('account_status', models.CharField(default='f', max_length=1)),
                ('account_number', models.CharField(default='', max_length=200)),
                ('account_name', models.CharField(default='', max_length=100)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('bank_slug', models.CharField(default='', max_length=50)),
                ('account_currency', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bank', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('star', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=1)),
                ('is_credit', models.BooleanField(default=False)),
                ('transaction_type', models.CharField(max_length=2)),
                ('provider', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reciever_number', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('transaction_type', models.CharField(default='', max_length=2)),
                ('provider', models.CharField(default='', max_length=12)),
                ('user_code', models.CharField(default='', max_length=50)),
                ('color_id', models.IntegerField(default=0)),
                ('avatar_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('last_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_transaction', to='transaction.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Autopayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uuid', models.CharField(default='', max_length=250)),
                ('transaction_type', models.CharField(max_length=3)),
                ('service_provider', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('amount_plan', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=2)),
                ('custom_days', models.IntegerField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_autopay', to=settings.AUTH_USER_MODEL)),
                ('last_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_autopay', to='transaction.transaction')),
            ],
        ),
    ]
