# Generated by Django 5.1.3 on 2024-12-10 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('F', 'failed'), ('P', 'pending'), ('S', 'success')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('at', 'airtime'), ('da', 'data'), ('ca', 'cable'), ('el', 'electricity'), ('bt', 'betting'), ('bs', 'bulk_sms'), ('dt', 'deposit')], max_length=2),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_7eb677_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_62e809_idx'),
        ),
    ]
